---
title: "Publications"
---

<div class="page-header">
<div class="kicker">Publications</div>

# Selected publications

<p class="lead">A curated list of publications that best represent my current research profile. The full list is available through Scopus and the institute publication page.</p>
</div>

## Selected paper

::: {.paper-card}
### Scaling Cooperative Mobile Multi-Robot Systems for Object Handling

**Tobias Recker**, Lukas Lachmayer, Annika Raatz. 2025 IEEE 21st International Conference on Automation Science and Engineering (CASE), Los Angeles, CA, USA, pp. 2562-2567.

This work presents a scalable cooperative mobile multi-robot framework for object handling and evaluates how CMMRS configurations can be scaled for handling large-scale components with multiple mobile manipulators.

<div class="link-list">
<a href="https://doi.org/10.1109/CASE58245.2025.11163753">DOI</a>
<a href="https://www.youtube.com/watch?v=7jzTUw5pK40">Video</a>
<a href="dissertation.html">Related dissertation</a>
</div>
:::

## Related publications

::: {.card-grid two}
::: {.paper-card}
### Design and control of flexible handling systems based on mobile cooperative multi-robot-systems

**Tobias Recker**, Annika Raatz. CIRP Annals, Volume 74, Issue 1, pp. 25-29, 2025.

<div class="link-list"><a href="https://doi.org/10.1016/j.cirp.2025.04.059">DOI</a></div>
:::

::: {.paper-card}
### Offline platform trajectory planning for print-while-drive additive manufacturing using mobile manipulators

Lukas Lachmayer, **Tobias Recker**, Hauke Heeren, Pitt Müller, Annika Raatz. IEEE CASE, pp. 1411-1416, 2025.

<div class="link-list"><a href="https://doi.org/10.1109/CASE58245.2025.11163995">DOI</a></div>
:::

::: {.paper-card}
### A Comparative Analysis of Different Semi-Rigid Formation Geometries Regarding Multi-Robot Cooperative Object Transport for Large-Scale Objects

**Tobias Recker**, Henrik Lurz, Lukas Lachmayer, Annika Raatz. IEEE CASE, 2024.
:::

::: {.paper-card}
### Time-Efficient Path Planning for Semi-Rigid Multi-Robot Formations

**Tobias Recker**, Sebastian Prophet, Annika Raatz. IEEE CASE, 2023.

<div class="link-list"><a href="https://doi.org/10.1109/CASE56687.2023.10260434">DOI</a></div>
:::

::: {.paper-card}
### Smooth Spline-based Trajectory Planning for Semi-Rigid Multi-Robot Formations

**Tobias Recker**, Henrik Lurz, Annika Raatz. IEEE CASE, pp. 1417-1422, 2022.

<div class="link-list"><a href="https://doi.org/10.1109/CASE49997.2022.9926604">DOI</a></div>
:::

::: {.paper-card}
### Additive Manufacturing using mobile robots: Opportunities and challenges for building construction

Kathrin Dörfler, Gido Dielemans, Lukas Lachmayer, **Tobias Recker**, Annika Raatz, Dirk Lowke, Markus Gerke. Cement and Concrete Research, Vol. 158, 106772, 2022.

<div class="link-list"><a href="https://doi.org/10.1016/j.cemconres.2022.106772">DOI</a></div>
:::
:::

## Profiles

<div class="button-row">
<a class="button primary" href="https://www.scopus.com/authid/detail.uri?authorId=57216780652">Scopus profile</a>
<a class="button" href="https://orcid.org/0000-0003-1632-0538">ORCID</a>
<a class="button" href="https://www.match.uni-hannover.de/en/institut/team/tobias-recker/publikationsliste">Institute publication list</a>
</div>

## BibTeX

A small starter BibTeX file is included in the website repository at `assets/data/references.bib`.
